# Generated by Django 4.1.2 on 2022-11-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='folders',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cw.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='folders',
            unique_together={('user', 'page')},
        ),
        migrations.CreateModel(
            name='PageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField()),
                ('comes_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comes_after', to='cw.page')),
                ('which', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which', to='cw.page')),
            ],
            options={
                'unique_together': {('which', 'comes_after')},
            },
        ),
    ]
