# Generated by Django 4.1.2 on 2022-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0002_rename_user_id_folders_user_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folders',
            new_name='Folder',
        ),
        migrations.AddField(
            model_name='page',
            name='data',
            field=models.TextField(default='Imagine this is a legit page body'),
            preserve_default=False,
        ),
    ]
