# Generated by Django 4.1.2 on 2022-11-22 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0004_alter_folder_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerelation',
            name='strength',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='pagerelation',
            constraint=models.CheckConstraint(check=models.Q(('strength__gte', 0), ('strength__lte', 100)), name='strength_range'),
        ),
    ]
